tasks:
  - init: npm install
    before: DATABASE_NAME=$DATABASE_NAME||dtdmysql mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME"
    command: npm run start -- --get-fares && npm run start -- --get-timetable && npm run start -- --get-routeing && npm run start -- --get-nfm64
image:
  file: .gitpod.Dockerfile