version: "3.7"
services:
  dtd2mysql:
    build: "."
    image: "dtd2mysql"
    volumes: 
      - .:/app
      - /app/node_modules
    links:
      - db:db
    env_file: .env
    depends_on:
      - db
  
  db:
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    env_file: .env
    depends_on:
      - db